# Generated by Django 5.2.5 on 2026-07-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_Cambio_Material_Vehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_cambio_cambio_material_vahicular', models.CharField(max_length=250)),
                ('Fecha_registro_cambio_material_vehicular', models.DateField()),
                ('Fecha_emision_cambio_material_vehicular', models.DateField()),
                ('Fecha_vencimiento_cambio_material_vehicular', models.DateField()),
                ('Padron_cambio_material_vehicular', models.CharField(max_length=250)),
                ('Placa_cambio_material_vehicular', models.CharField(max_length=250)),
                ('Cantidad_cambio_material_vehicular', models.CharField(max_length=250)),
                ('Comentario_cambio_material_vehicular', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_Hora_Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_tabla_hora_extra', models.CharField(max_length=250)),
                ('Nombre_hora_extra', models.CharField(max_length=250)),
                ('Fecha_hora_extra', models.DateField()),
                ('Hora_inicio_extra', models.TimeField()),
                ('Hora_final_extra', models.TimeField()),
                ('Cantidad_hora_extra', models.CharField(max_length=250)),
                ('Comentario_hora_extra', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_tabla_horario', models.CharField(max_length=250)),
                ('Nombre_tabla_horario', models.TextField(max_length=250)),
                ('Hora_inicio_horario', models.TimeField()),
                ('Hora_final_horario', models.TimeField()),
                ('Comentario_horario', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_tabla_inventario', models.CharField(max_length=250)),
                ('Fecha_tabla_inventario', models.DateField()),
                ('Nombre_tabla_inventario', models.CharField(max_length=250)),
                ('Descripcion_tabla_inventario', models.CharField(max_length=250)),
                ('Cantidad_tabla_inventario', models.CharField(max_length=250)),
                ('Comentario_tabla_inventario', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_Recepcion_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_recepcion_material', models.CharField(max_length=250)),
                ('Fecha_recepcion_material', models.DateField()),
                ('Nombre_empresa_recepcion_material', models.CharField(max_length=250)),
                ('Nombre_material_recepcion_material', models.CharField(max_length=250)),
                ('Numero_factura_recepcion_material', models.CharField(max_length=250)),
                ('Codigo_recepcion_material', models.CharField(max_length=250)),
                ('Cantidad_recepcion_material', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_Salida_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_tabla_salida_material', models.CharField(max_length=250)),
                ('Fecha_salida_material', models.DateField()),
                ('Nombre_salida_material', models.CharField(max_length=250)),
                ('Descripcion_salida_material', models.CharField(max_length=250)),
                ('Padron_salida_material', models.CharField(max_length=250)),
                ('Cantidad_salida_material', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_Tecnico_Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_tabla_tecnico_mecanica', models.CharField(max_length=250)),
                ('Fecha_tabla_tecnico_mecanica', models.DateField()),
                ('Nombre_tabla_tecnico_mecanica', models.CharField(max_length=250)),
                ('Placa_tabla_tecnico_mecanica', models.CharField(max_length=250)),
                ('Padron_tabla_tecnico_mecanico', models.CharField(max_length=250)),
                ('Trabajo_tabla_tecnico_mecanico', models.CharField(max_length=250)),
                ('Comentario_tabla_tecnico_mecanico', models.CharField(max_length=250)),
            ],
        ),
    ]
