# Generated by Django 5.2.5 on 2026-07-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla_horario',
            name='Comentario_horario',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tabla_horario',
            name='Nombre_tabla_horario',
            field=models.CharField(max_length=250),
        ),
    ]
