# Generated by Django 5.2.5 on 2026-07-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tabla_horario_comentario_horario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_Horario_Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_tabla_horario', models.CharField(max_length=250)),
                ('Nombre_tabla_horario', models.CharField(max_length=250)),
                ('Fecha_inicio_horario', models.DateField()),
                ('Hora_inicio_horario', models.TimeField()),
                ('Hora_final_horario', models.TimeField()),
                ('Comentario_horario', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Tabla_Horario',
        ),
    ]
